meta:
  site_title: "state.js"
  site_subtitle: "well-behaved JavaScript"
  site_language: "en"
  absolute_baseurl: http://statejs.org
  domain: statejs.org
  author:
    full_name: Nick Fargo
    short_name: nickfargo
    email: nick.fargo@gmail.com

tag_dir: tag
pygments: true
markdown: rdiscount
permalink: pretty

packages:
  state:
    version: 0.0.5
    size: 149kB
    size_gz: 8.6kB
  omicron:
    version: 0.1.7
    size: 18kB
    size_gz: 2.1kB
