meta:
  site_title: "state.js"
  site_subtitle: "well-behaved JavaScript"
  site_language: "en"
  absolute_baseurl: http://statejs.org
  domain: statejs.org
  author:
    full_name: Nick Fargo
    short_name: nickfargo
    email: nick.fargo@gmail.com
    github: nickfargo
    twitter: nickfargo
  license: MIT
  license_url: http://github.com/nickfargo/state/blob/master/LICENSE 

tag_dir: tag
pygments: true
markdown: rdiscount
permalink: /blog/:title
exclude: art/*, diagrams/*

packages:
  state:
    version: 0.0.8
    size: 147kB
    size_gz: 9.3kB
  omicron:
    version: 0.1.9
    size: 25kB
    size_gz: 2.5kB
