meta:
  site_title: "state.js"
  site_subtitle: "well-behaved JavaScript"
  site_language: "en"
  absolute_baseurl: http://statejs.org
  domain: statejs.org
  author:
    full_name: Nick Fargo
    short_name: nickfargo
    email: nick.fargo@gmail.com

tag_dir: tag
pygments: true
markdown: rdiscount
permalink: pretty
exclude: art/*

packages:
  state:
    version: 0.0.6
    size: 136kB
    size_gz: 8.5kB
  omicron:
    version: 0.1.8
    size: 19kB
    size_gz: 2.1kB
