meta:
  site_title: "state.js"
  site_subtitle: "well-behaved JavaScript"
  site_language: "en"
  absolute_baseurl: http://statejs.org
  domain: statejs.org
  author:
    full_name: Nick Fargo
    short_name: nickfargo
    email: nick.fargo@gmail.com
    github: nickfargo
    twitter: nickfargo
  license: MIT
  license_url: http://github.com/nickfargo/state/blob/master/LICENSE

tag_dir: tag
pygments: true
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
exclude: [ art, diagrams ]

packages:
  state:
    version: 0.1.2
    size: 97.4kB
    size_gz: 15.4kB
